osx_image: xcode8.0
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
 - echo "3.0" > .swift-version
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
