language: objective-c
osx_image: xcode8.0

script:
- xcodebuild clean build test -project EasyGradients.xcworkspace -scheme EasyGradients GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash)
