osx_image: xcode8
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example #
 - echo "3.0" > .swift-version #
script:
- set -o pipefail && xcodebuild test -workspace Example/EasyGradients.xcworkspace -scheme EasyGradients-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
